//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRealTimeDriverService")]
    public interface IRealTimeDriverService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriverService/Register", ReplyAction="http://tempuri.org/IRealTimeDriverService/RegisterResponse")]
        bool Register(int id, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriverService/Register", ReplyAction="http://tempuri.org/IRealTimeDriverService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(int id, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriverService/SendMessage", ReplyAction="http://tempuri.org/IRealTimeDriverService/SendMessageResponse")]
        bool SendMessage(int id, int address, string value, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriverService/SendMessage", ReplyAction="http://tempuri.org/IRealTimeDriverService/SendMessageResponse")]
        System.Threading.Tasks.Task<bool> SendMessageAsync(int id, int address, string value, byte[] signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeDriverServiceChannel : RealTimeUnit.ServiceReference1.IRealTimeDriverService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeDriverServiceClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference1.IRealTimeDriverService>, RealTimeUnit.ServiceReference1.IRealTimeDriverService {
        
        public RealTimeDriverServiceClient() {
        }
        
        public RealTimeDriverServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeDriverServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Register(int id, string path) {
            return base.Channel.Register(id, path);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(int id, string path) {
            return base.Channel.RegisterAsync(id, path);
        }
        
        public bool SendMessage(int id, int address, string value, byte[] signature) {
            return base.Channel.SendMessage(id, address, value, signature);
        }
        
        public System.Threading.Tasks.Task<bool> SendMessageAsync(int id, int address, string value, byte[] signature) {
            return base.Channel.SendMessageAsync(id, address, value, signature);
        }
    }
}
